---

- ansible.builtin.lineinfile:
    path: "{{ ansible_facts.env.HOME }}/.bashrc"
    regexp: ^export DOCKER_HOST=
    line: export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock

- ansible.builtin.shell:
    cmd: "{{ item.cmd | default(['curl', '--location', '--output', item.file, item.url | default(omit), '&&', 'chmod', '+x', item.file] | join(' ')) }}"
    creates: "{{ item.file }}"
  become: yes
  loop:
    - url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
      file: /usr/local/bin/docker-compose
    - cmd: curl --location https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      file: /usr/local/bin/helm
    - url: https://dl.k8s.io/release/{{ lookup('ansible.builtin.url', 'https://dl.k8s.io/release/stable.txt') }}/bin/linux/amd64/kubectl
      file: /usr/local/bin/kubectl
    - url: https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
      file: /usr/local/bin/minikube

- ansible.builtin.systemd_service:
    name: podman.socket
    enabled: yes
    scope: user

- ansible.builtin.user:
    name: "{{ ansible_facts.user_id }}"
    append: yes
    groups: libvirt
  become: yes
